#!/bin/sh

make allnoconfig # To remove all settings to make the kernel minimal.

# Platform & Compression
./scripts/config --enable 64BIT # Disable if your system is 32bit.
./scripts/config --enable KERNEL_LZ4 # Fastest to Boot. You need to emerge app-arch/lz4 before compiling the kernel.

# Gentoo & OpenRC & Portage
./scripts/config --enable EXPERT # Needed for below settings.
./scripts/config --enable GENTOO_LINUX
./scripts/config --enable GENTOO_LINUX_UDEV
./scripts/config --enable GENTOO_LINUX_PORTAGE
./scripts/config --enable GENTOO_LINUX_INIT_SCRIPT
./scripts/config --enable NET
./scripts/config --enable DEVTMPFS_MOUNT
./scripts/config --enable STANDALONE
./scripts/config --enable PREVENT_FIRMWARE_BUILD
./scripts/config --enable BLK_DEV_SD # Disk support (SSD, HDD etc.)
./scripts/config --enable BLK_DEV_BSG # Important for getting disk information.
./scripts/config --enable ATA # Your hard drive won't work without this.
./scripts/config --enable SATA_AHCI # Also for hard drive.
./scripts/config --enable SECTION_MISMATCH_WARN_ONLY # Otherwise build may fail.

# Block Layer | INFO: https://lwn.net/Articles/681763/
./scripts/config --enable BLOCK
./scripts/config --enable BLK_WBT
./scripts/config --enable BLK_WBT_MQ

# UEFI & Efistub
./scripts/config --enable ACPI # Needed for below settings
./scripts/config --enable X86_PM_TIMER # Needed for below
./scripts/config --enable ACPI_BUTTON # needed for shutdown from cmdline.
./scripts/config --enable PARTITION_ADVANCED # Needed for below settings
./scripts/config --enable EFI # Needed for UEFI Boot Mode
./scripts/config --enable EFI_PARTITION # Needed for GPT Labeled Partitions
./scripts/config --enable EFI_STUB # Can be disabled if not using efistub
./scripts/config --enable EFIVAR_FS # efibootmgr won't work without this
./scripts/config --enable CMDLINE_BOOL # Can be disabled if not using efistub
./scripts/config --set-str CMDLINE root=PARTUUID=c32f45b5-177e-2344-8506-22aeebcee05b # >> CHANGE THIS WITH YOURS <<.
./scripts/config --disable EFI_HANDOVER_PROTOCOL # Deprecated

# USB Keyboard & External HDD (All settings needed except "persist" or "storage")
./scripts/config --enable HID_SUPPORT
./scripts/config --enable HID_GENERIC
./scripts/config --enable USB
./scripts/config --enable USB_HID
./scripts/config --enable USB_SUPPORT
./scripts/config --enable USB_DEFAULT_PERSIST # Uninterrupted USB connection.
./scripts/config --enable USB_XHCI_HCD # USB 3.1 Support (Also works with older versions)
./scripts/config --enable USB_STORAGE # Mass Storage Devices
./scripts/config --enable INPUT_EVDEV # Can't start window managers without this.
./scripts/config --enable USB_PCI

# Nvidia Proprietary & Wayland Support
# Load Nvidia Modules
./scripts/config --enable MODULES
## MTRR & PAT https://wiki.gentoo.org/wiki/MTRR_and_PAT
./scripts/config --enable MTRR
./scripts/config --enable MTRR_SANITIZER
./scripts/config --set-val MTRR_SANITIZER_ENABLE_DEFAULT 1
./scripts/config --set-val MTRR_SANITIZER_SPARE_REG_NR_DEFAULT 0 # Can be different for you. Look at the Article.
./scripts/config --enable X86_PAT
## DRM (Needed for Wayland with proprietary nvidia-drivers otherwise should be disabled)
./scripts/config --enable DRM # x11-drivers/nvidia-drivers mentions these
./scripts/config --module DRM_SIMPLEDRM #Needed for DRM_KMS_HELPER
## Framebuffer Driver (To be able to boot with Nvidia GPU and UEFI)
./scripts/config --enable FB
./scripts/config --enable FB_EFI
## Gentoo Nvidia Help Page
./scripts/config --enable GCC_PLUGINS
./scripts/config --enable VGA_CONSOLE # Needed for booting to tty.
./scripts/config --enable FRAMEBUFFER_CONSOLE # Needed for booting to tty.

# CPU & Performance
./scripts/config --enable SMP # Support multi-core processors
./scripts/config --disable X86_MPPARSE # This is for old systems.
./scripts/config --enable HIGH_RES_TIMERS
./scripts/config --enable SCHED_OMIT_FRAME_POINTER # Use single wchan output.
./scripts/config --enable SCHED_MC
./scripts/config --enable SCHED_MC_PRIO
./scripts/config --enable PCI # needed for below setting
./scripts/config --enable PCI_MSI # needed for below setting
./scripts/config --enable MCORE2 # Change this according to CPU.
./scripts/config --enable CC_OPTIMIZE_FOR_PERFORMANCE
./scripts/config --enable HZ_1000 # Fastest Available Tick Rate
./scripts/config --enable PREEMPT # Low Latency Desktop Setting
./scripts/config --enable SCHED_AUTOGROUP # known to increase performance
./scripts/config --disable DMI # Required for non-UEFI.
./scripts/config --set-val NR_CPUS 16 # Thread number for your CPU.
./scripts/config --disable SCHED_CLUSTER # For multi-CPU systems.
./scripts/config --disable CPU_ISOLATION # Makes CPU uninterruptable for critical tasks.
./scripts/config --enable MICROCODE
./scripts/config --enable MICROCODE_INTEL
./scripts/config --enable FW_LOADER
./scripts/config --set-str EXTRA_FIRMWARE intel-ucode/06-9e-0c # look at intel-microcode page
./scripts/config --set-str EXTRA_FIRMWARE_DIR /lib/firmware
./scripts/config --enable CPU_FREQ_DEFAULT_GOV_PERFORMANCE
./scripts/config --enable JUMP_LABEL
./scripts/config --enable SLAB_MERGE_DEFAULT
./scripts/config --disable SLUB_CPU_PARTIAL
./scripts/config --enable COMPACTION
./scripts/config --enable PCIE_BUS_PERFORMANCE
./scripts/config --enable SCSI_SCAN_ASYNC #faster boot
./scripts/config --enable UNWINDER_ORC
./scripts/config --enable HIGH_RES_TIMERS
./scripts/config --disable COMPAT_BRK
./scripts/config --enable ZONE_DMA
./scripts/config --enable INIT_STACK_NONE
./scripts/config --enable RANDSTRUCT_NONE
./scripts/config --enable CRYPTO_MANAGER_DISABLE_TESTS
./scripts/config --enable DEBUG_INFO_NONE
./scripts/config --enable IO_DELAY_NONE

# Minimizing Logs
./scripts/config --set-val CONSOLE_LOGLEVEL_DEFAULT 1
./scripts/config --set-val CONSOLE_LOGLEVEL_QUIET 1
./scripts/config --set-val MESSAGE_LOGLEVEL_DEFAULT 1

# Log Buffer Size for CPU (Change for your preference: 12 is the smallest)
./scripts/config --set-val LOG_BUF_SHIFT 12
./scripts/config --set-val LOG_CPU_MAX_BUF_SHIFT 12
./scripts/config --set-val PRINTK_SAFE_LOG_BUF_SHIFT 12

#SelectCPU
./scripts/config --enable PROCESSOR_SELECT
./scripts/config --enable CPU_SUP_INTEL # You may need to change if using AMD.

# NVMe SSD Support
./scripts/config --enable BLK_DEV_NVME
./scripts/config --enable NVME_MULTIPATH

# Network Drivers & Performance
./scripts/config --enable PACKET
./scripts/config --enable INET # Internet won't work without this
./scripts/config --enable TCP_CONG_ADVANCED
./scripts/config --enable TCP_CONG_BBR
./scripts/config --enable DEFAULT_BBR # You may look up BBR scheduling. It's promising.
./scripts/config --enable MPTCP
./scripts/config --enable NET_SCHED # Needed for below.
./scripts/config --enable NET_SCH_FQ # Needed for BBR.
./scripts/config --enable NET_SCH_DEFAULT # Needed for above.
./scripts/config --enable DEFAULT_FQ # Needed for above.
./scripts/config --enable PCPU_DEV_REFCNT

# Network Performance
./scripts/config --enable TCP_CONG_ADVANCED
./scripts/config --enable TCP_CONG_BBR
./scripts/config --enable DEFAULT_BBR
./scripts/config --disable TCP_CONG_BIC
./scripts/config --disable TCP_CONG_CUBIC
./scripts/config --disable TCP_CONG_WESTWOOD
./scripts/config --disable TCP_CONG_HTCP

# Ethernet Driver & OpenVPN (Can be disabled if not planned to use)
./scripts/config --enable NETDEVICES # needed for below settings
./scripts/config --enable NET_CORE # needed for vpn
./scripts/config --module TUN # OpenVPN
./scripts/config --enable ETHERNET
./scripts/config --enable NET_VENDOR_INTEL
./scripts/config --enable E1000E # Ethernet driver. Try "lspci -k" command to see your ethernet driver.

# SOUND
./scripts/config --enable SOUND
./scripts/config --enable SND
./scripts/config --enable SND_HDA_INTEL
./scripts/config --enable SND_HDA_CODEC_REALTEK
./scripts/config --enable SND_USB_AUDIO

# ADDITIONAL NEEDED
./scripts/config --enable VT_HW_CONSOLE_BINDING
./scripts/config --enable NLS_CODEPAGE_437
./scripts/config --enable NLS_UTF8
./scripts/config --set-str NLS_DEFAULT utf8
./scripts/config --enable NLS_ASCII
./scripts/config --enable SECTION_MISMATCH_WARN_ONLY

# ELF Files (Needed to run Gentoo)
./scripts/config --enable BINFMT_ELF
./scripts/config --enable BINFMT_MISC

# Enable basic terminal support (all needed)
./scripts/config --enable TTY
./scripts/config --enable VT
./scripts/config --enable VT_CONSOLE
./scripts/config --enable UNIX98_PTYS
./scripts/config --enable SERIAL_8250
./scripts/config --enable SERIAL_8250_PCI
./scripts/config --set-val SERIAL_8250_NR_UARTS 3 # If you have more PCI devices, increase it.)
./scripts/config --set-val SERIAL_8250_RUNTIME_UARTS 3 # Same as above.

# Filetypes
./scripts/config --enable EXT4_FS # Most used and supported file type for Linux.
./scripts/config --enable EXT4_USE_FOR_EXT2 # Use ext4 driver for ext2. It makes the kernel smaller.
./scripts/config --enable FUSE_FS # You can use this with ntfs3g to mount ntfs usb drives.
./scripts/config --enable VFAT_FS # For mounting boot partition
./scripts/config --set-str FAT_DEFAULT_IOCHARSET iso8859-1
./scripts/config --enable PROC_FS # virtual file system to look at system devices. You may need this.
./scripts/config --enable SYSFS # This is needed as default.
./scripts/config --enable TMPFS_XATTR # Needed for portage.

# Native Language Support (Needed for some programs and functions)
./scripts/config --set-str NLS_DEFAULT utf8
./scripts/config --enable NLS_CODEPAGE_437 # USA Canada
./scripts/config --enable NLS_ASCII # USA
./scripts/config --enable NLS_ISO8859_1 # Western EU (Needed)
./scripts/config --enable NLS_UTF8
./scripts/config --enable UNICODE

# Miscs to disable (unneeded)
./scripts/config --disable SGETMASK_SYSCALL # deprecated
./scripts/config --disable SYSFS_SYSCALL # deprecated
./scripts/config --disable FHANDLE # Not needed if you don't use userspace file servers.
./scripts/config --disable BUG # Not needed if not debugging.
./scripts/config --disable ELF_CORE # not needed if not debugging.
./scripts/config --disable PCSPKR_PLATFORM # not needed if not using speakers.
./scripts/config --disable KALLSYMS # debugging
./scripts/config --disable CPU_SUP_ZHAOXIN # Disable unneeded CPU support.
./scripts/config --disable CPU_SUP_CENTAUR
./scripts/config --disable CPU_SUP_HYGON
./scripts/config --disable CPU_SUP_AMD
./scripts/config --disable X86_16BIT # enable if you need Wine
./scripts/config --disable X86_VSYSCALL_EMULATION # for legacy apps
./scripts/config --disable X86_5LEVEL # for huge ram support
./scripts/config --disable X86_KERNEL_IBT # increased security
./scripts/config --disable X86_INTEL_MEMORY_PROTECTION_KEYS # not needed
./scripts/config --disable RANDOMIZE_BASE # increased security
./scripts/config --disable MODIFY_LDT_SYSCALL
./scripts/config --disable ACPI_SPCR_TABLE
./scripts/config --disable ACPI_REV_OVERRIDE_POSSIBLE
./scripts/config --disable ACPI_AC # Don't disable on laptops.
./scripts/config --disable ACPI_BATTERY # Don't disable on laptops.
./scripts/config --disable ACPI_FAN # software based fan control.
./scripts/config --disable ACPI_THERMAL
./scripts/config --disable ACPI_PCC
./scripts/config --disable ACPI_PRMT
./scripts/config --disable PCI_MMCONFIG # not needed
./scripts/config --disable ISA_DMA_API # not needed
./scripts/config --disable VMAP_STACK # increased security
./scripts/config --disable RANDOMIZE_KSTACK_OFFSET # increased security
./scripts/config --disable MSDOS_PARTITION # not needed
./scripts/config --disable COREDUMP # debugging
./scripts/config --disable SPARSEMEM_VMEMMAP # virtual machines
./scripts/config --disable VM_EVENT_COUNTERS # not needed
./scripts/config --disable SECRETMEM # not needed
./scripts/config --disable ETHTOOL_NETLINK # not needed
./scripts/config --disable PCIEASPM # not needed
./scripts/config --disable PCI_QUIRKS # legacy
./scripts/config --disable VGA_ARB # legacy
./scripts/config --disable FIRMWARE_MEMMAP # debugging
./scripts/config --disable EFI_DXE_MEM_ATTRIBUTES # not needed
./scripts/config --disable PNP_DEBUG_MESSAGES
./scripts/config --disable SCSI_PROC_FS # legacy
./scripts/config --disable SCSI_LOWLEVEL # not needed
./scripts/config --disable ATA_VERBOSE_ERROR
./scripts/config --disable ATA_FORCE
./scripts/config --disable ATA_ACPI
./scripts/config --disable SATA_PMP # port multiplying
./scripts/config --disable ATA_SFF # legacy
./scripts/config --disable USB_NET_DRIVERS # I don't use adapters.
./scripts/config --disable WLAN # This is for WIRELESS Internet.
# Unneeded Ethernet Drivers (Remove your driver from this list)
./scripts/config --disable NET_VENDOR_3COM
./scripts/config --disable NET_VENDOR_ADAPTEC
./scripts/config --disable NET_VENDOR_AGERE
./scripts/config --disable NET_VENDOR_ALACRITECH
./scripts/config --disable NET_VENDOR_ALTEON
./scripts/config --disable NET_VENDOR_AMAZON
./scripts/config --disable NET_VENDOR_AMD
./scripts/config --disable NET_VENDOR_AQUANTIA
./scripts/config --disable NET_VENDOR_ARC
./scripts/config --disable NET_VENDOR_ASIX
./scripts/config --disable NET_VENDOR_ATHEROS
./scripts/config --disable NET_VENDOR_BROADCOM
./scripts/config --disable NET_VENDOR_CADENCE
./scripts/config --disable NET_VENDOR_CAVIUM
./scripts/config --disable NET_VENDOR_CHELSIO
./scripts/config --disable NET_VENDOR_CISCO
./scripts/config --disable NET_VENDOR_CORTINA
./scripts/config --disable NET_VENDOR_DAVICOM
./scripts/config --disable NET_VENDOR_DEC
./scripts/config --disable NET_VENDOR_DLINK
./scripts/config --disable NET_VENDOR_EMULEX
./scripts/config --disable NET_VENDOR_ENGLEDER
./scripts/config --disable NET_VENDOR_EZCHIP
./scripts/config --disable NET_VENDOR_FUNGIBLE
./scripts/config --disable NET_VENDOR_GOOGLE
./scripts/config --disable NET_VENDOR_HUAWEI
./scripts/config --disable NET_VENDOR_I825XX
./scripts/config --disable E1000E_HWTSNET_VENDOR_WANGXUN
./scripts/config --disable NET_VENDOR_WANGXUN
./scripts/config --disable NET_VENDOR_LITEX
./scripts/config --disable NET_VENDOR_MARVELL
./scripts/config --disable NET_VENDOR_MELLANOX
./scripts/config --disable NET_VENDOR_MICREL
./scripts/config --disable NET_VENDOR_MICROCHIP
./scripts/config --disable NET_VENDOR_MICROSEMI
./scripts/config --disable NET_VENDOR_MICROSOFT
./scripts/config --disable NET_VENDOR_MYRI
./scripts/config --disable NET_VENDOR_NI
./scripts/config --disable NET_VENDOR_NATSEMI
./scripts/config --disable NET_VENDOR_NETERION
./scripts/config --disable NET_VENDOR_NETRONOME
./scripts/config --disable NET_VENDOR_NVIDIA
./scripts/config --disable NET_VENDOR_OKI
./scripts/config --disable NET_VENDOR_PACKET_ENGINES
./scripts/config --disable NET_VENDOR_PENSANDO
./scripts/config --disable NET_VENDOR_QLOGIC
./scripts/config --disable NET_VENDOR_BROCADE
./scripts/config --disable NET_VENDOR_QUALCOMM
./scripts/config --disable NET_VENDOR_RDC
./scripts/config --disable NET_VENDOR_REALTEK
./scripts/config --disable NET_VENDOR_RENESAS
./scripts/config --disable NET_VENDOR_ROCKER
./scripts/config --disable NET_VENDOR_SAMSUNG
./scripts/config --disable NET_VENDOR_SEEQ
./scripts/config --disable NET_VENDOR_SILAN
./scripts/config --disable NET_VENDOR_SIS
./scripts/config --disable NET_VENDOR_SOLARFLARE
./scripts/config --disable NET_VENDOR_SMSC
./scripts/config --disable NET_VENDOR_SOCIONEXT
./scripts/config --disable NET_VENDOR_STMICRO
./scripts/config --disable NET_VENDOR_SUN
./scripts/config --disable NET_VENDOR_TEHUTI
./scripts/config --disable NET_VENDOR_TI
./scripts/config --disable NET_VENDOR_VERTEXCOM
./scripts/config --disable NET_VENDOR_VIA
./scripts/config --disable NET_VENDOR_WIZNET
./scripts/config --disable NET_VENDOR_XILINX

./scripts/config --disable INPUT_LEDS # not needed
./scripts/config --disable CONSOLE_TRANSLATIONS # not needed
./scripts/config --disable SERIAL_8250_DEPRECATED_OPTIONS # deprecated
./scripts/config --disable SERIAL_8250_PNP # not needed
./scripts/config --disable SERIAL_8250_EXAR # not needed
# generally not needed
./scripts/config --disable SERIAL_8250_LPSS
./scripts/config --disable SERIAL_8250_MID
./scripts/config --disable SERIAL_8250_PERICOM
./scripts/config --disable DEVPORT
./scripts/config --disable ACPI_I2C_OPREGION
./scripts/config --disable I2C_COMPAT
./scripts/config --disable I2C_HELPER_AUTO
./scripts/config --disable PTP_1588_CLOCK
./scripts/config --disable X86_PKG_TEMP_THERMAL
./scripts/config --disable DRM_FBDEV_EMULATION
./scripts/config --disable SND_PCM_TIMER
./scripts/config --disable SND_SUPPORT_OLD_API
./scripts/config --disable SND_VERBOSE_PROCFS
./scripts/config --disable SND_CTL_FAST_LOOKUP
./scripts/config --disable SND_DRIVERS
./scripts/config --disable SND_X86
./scripts/config --disable PROC_SYSCTL # needed for changing kernel parameters without reboot
./scripts/config --disable PROC_PAGE_MONITOR
./scripts/config --disable NETWORK_FILESYSTEMS
./scripts/config --set-str LSM " " # security
./scripts/config --disable CRYPTO_HW
./scripts/config --enable INIT_STACK_NONE # security
# Debugging
./scripts/config --disable DEBUG_MISC
./scripts/config --disable SLUB_DEBUG
./scripts/config --disable DEBUG_MEMORY_INIT
./scripts/config --disable SCHED_DEBUG
./scripts/config --disable DEBUG_PREEMPT
./scripts/config --disable STACKTRACE
./scripts/config --disable RCU_TRACE
./scripts/config --disable EARLY_PRINTK
./scripts/config --disable X86_DEBUG_FPU
./scripts/config --disable GENTOO_PRINT_FIRMWARE_INFO

# make -j$(nproc) && emerge x11-drivers/nvidia-drivers && make modules_install && cp /usr/src/linux/arch/x86/boot/bzImage /boot/EFI/BOOT/BOOTX64.EFI
