#!/bin/sh

alias vim="nvim" vimdiff="nvim -d"

sc() {
  myscripts=$(find $HOME/.local/bin -type f)
  chosen=$(echo "$myscripts" | sed 's|.*/||' | fzf)
  $EDITOR "$(echo "$myscripts" | grep "$chosen")"
}

po() { doas $EDITOR $(find /etc/portage -type f | fzf) }

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	cat="bat -P" \
	yt="yt-dlp" \
	ffmpeg="ffmpeg -hide_banner" \

alias \
	ll="eza -lh --group-directories-first --color=always --color-scale=all --color-scale-mode=fixed --icons=always --no-quotes --smart-group -s size --total-size --no-user --no-permissions" \
	ls="eza --group-directories-first --color=always --icons --no-quotes -s name" \
	lsf="eza -f --group-directories-first --color=always --icons --no-quotes -s name" \
	lsd="eza -D --group-directories-first --color=always --icons --no-quotes -s name" \
	lst="eza -lh --group-directories-first --color=always --color-scale --icons --no-quotes --smart-group -s time --total-size --no-user --no-permissions" \
	chrome="nvim .librewolf/*/chrome/userChrome.css" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

alias \
	ka="killall" \
	sdn="doas maintain" \
	e="$EDITOR" \
	v="$EDITOR" \
	emg="doas emerge --ask --update --newuse @world" \
