#!/bin/zsh

export PATH="$PATH:$HOME/.local/bin"

setopt PROMPT_SP

export BROWSER="librewolf"
export EDITOR="nvim"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_VIDEOS_DIR="$HOME/videos"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export FZF_DEFAULT_OPTS="--layout=reverse --height 80%"

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Hyprland >/dev/null 2>&1 && exec "/home/emre/.config/hypr/start.sh"
